config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  resources :hotels do
    resources :rooms
    member do
      delete :purge_avatar
    end
    delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'
  end
  # resources :rooms

  namespace :admin do
    resources :users, only: %i[index create]
  end

  delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'

  root 'hotels#index'
end

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
<header class="p-3 bg-dark text-white">
  <div class="container">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <%= link_to 'All hotels', hotels_path, class: 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" 
                href="#" id="navbarDropdown" 
                role="button" data-toggle="dropdown" 
                aria-haspopup="true" 
                aria-expanded="false"> <%= current_user.name_or_email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit profile', edit_user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Log out', session_path, :method => :delete, class: 'dropdown-item' %>
            </div>
          </li>
          <% else %>
          <li><%= nav_tab 'Sign up', new_user_path, class: 'nav-link px-2' %>
          </li>
          <li><%= nav_tab 'Log in', new_session_path, class: 'nav-link px-2' %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  </div>
</header>
<% end %>