config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  resources :hotels do
    resources :rooms
    member do
      delete :purge_avatar
    end
    delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'
  end
  # resources :rooms

  namespace :admin do
    resources :users, only: %i[index create]
  end

  delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'

  root 'hotels#index'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  has_many_attached :images

  belongs_to :hotel
  belongs_to :user

  validates :room_type, presence: true
  validates :price_per_night, presence: true
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :find_hotel!
  before_action :find_room!, only: %i[edit update destroy show]

  def update
    if @room.update room_update_params
      flash[:success] = 'Room saved'
      redirect_to hotel_path(@hotel, anchor: dom_id(@room))
    else
      render :edit
    end
  end

  def edit
    @room = @hotel.rooms.find params[:id]
  end

  def new
    @room = @hotel.rooms.build
  end

  def create
    # current_user.hotels.build hotel_params
    @room = @hotel.rooms.build room_create_params
    if @room.save
      flash[:success] = 'Room created!'
      redirect_to hotel_path(@hotel, anchor: "room-#{@room.id}")
    else
      @pagy, @rooms = pagy @hotel.rooms.order(created_at: :desc)
      render :new
    end
  end

  def show
    @room = @hotel.rooms.find params[:id]
  end

  def destroy
    @room = @hotel.rooms.find params[:id]
    @room.destroy
    flash[:success] = 'Room deleted!'
    redirect_to hotel_path(@hotel)
  end

  private

  def room_create_params
    params.require(:room).permit(:price_per_night, :room_type, :link_img, :bed_type, :number_of_people, :booking_type,
                                 :number_of_beds, :food, :comforts, images: []).merge(user_id: current_user.id)
  end

  def room_update_params
    params.require(:room).permit(:price_per_night, :room_type, :link_img, :bed_type, :number_of_people, :booking_type,
                                 :number_of_beds, :food, :comforts, images: [])
  end

  def find_hotel!
    @hotel = Hotel.find params[:hotel_id]
  end

  def find_room!
    @room = @hotel.rooms.find params[:id]
  end
end

app/helpers/rooms_helper.rb
# frozen_string_literal: true

module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= render 'shared/errors', object: @room %>
<%= form_with model: [@hotel, @room] do |f| %>

<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :room_type %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :room_type, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :price_per_night %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :price_per_night, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :bed_type %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :bed_type, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :number_of_people %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :number_of_people, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :booking_type %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :booking_type, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :food %>
  </div>

  <div class="col-sm-10">
    <%= f.text_field :food, class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :images %>
  </div>

  <div class="col-sm-10">
    <%= f.file_field :images, multiple: true, class: 'form-control' %>
  </div>
</div>


<div class="photo-gallery mb-4">
    <div class="container">
      <div class="row photos">

        <% if @room.images.attached? %>
        <% @room.images.each do |image| %>

        <div class="col-sm-4 col-md-3 col-lg-2 item">
          <%= link_to image, data: { lightbox: "room"} do %>
          <%= image_tag image, class: 'img-thumbnail' %>
          <% end %>
          <%= link_to "Delete image", purge_attachement_path(image), method: :delete %>
        </div>
        <% end %>
        <% end %>

      </div>
    </div>
  </div>


<%= f.submit "Submit!", class: 'btn btn-primary' %>
<% end %>

app/views/rooms/_room.html.erb
<%= tag.article class: 'mb-3 card', id: dom_id(@room) do %>

<div class="card-body">
  <section class="card-text">
    <div class="row mb-3">
      <div class="col-md-9">
        <h4 class="card-title mb-5"><%= room.room_type %></h4>
        <p class="mt-0 mb-0">Bed type:: <%= room.bed_type %></p>
        <p class="mt-0 mb-0">Number of guests: <%= room.number_of_people %></p>
        <p class="mt-0 mb-0">Food: <%= room.food %> $</p>
        <p class="mt-0 mb-0">Comforts: <%= room.comforts %></p>
        <p class="mt-0 mb-0">Booking type: <%= room.booking_type %></p>
      </div>

      <div class="col">
        <h3><%= room.price_per_night %> $</h3>
        <%= link_to 'Show', hotel_room_path(@hotel, room), class: 'btn btn-primary btn-sm' %>
        <%= link_to 'Edit', edit_hotel_room_path(@hotel, room), class: 'btn btn-warning btn-sm' %>
        <%= link_to 'Delete', hotel_room_path(@hotel, room), class: 'btn btn-danger btn-sm', data: {method: :delete, confirm: "Are you sure"} %>
      </div>
    </div>
    
    <div class="photo-gallery mb-4">
      <div class="container">
        <div class="row photos">

          <% if room.images.attached? %>
          <% room.images.each do |image| %>

          <div class="col-sm-3 col-md-1 col-lg-2 item">
            <%= image_tag image, class: 'img-thumbnail' %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>
<% end %>

app/views/rooms/edit.html.erb
<% provide :page_title, 'Edit room' %>
<% currently_at 'Rooms' %>

<h1 class="mb-4">Edit room</h1>
 <%= render 'form' %>

app/views/rooms/new.html.erb
<% provide :page_title, 'New room' %>
<% currently_at 'Rooms' %>

<h1 class="mb-4">Create room</h1>
 <%= render 'form' %>

app/views/rooms/show.html.erb
<% provide :page_title, 'Edit room' %>
<% currently_at 'Rooms' %>
<%= tag.article class: 'mb-3 card', id: dom_id(@room) do %>

<div class="card-body">
  <section class="card-text">
    <p>
      <%=link_to @hotel.title, hotel_path(@hotel), class: "link-secondary" %> 
    </p>
    <h2 class="card-title mb-5"><%= @room.room_type %></h2>

    <div class="row">
      <div class="col-md-9">
        <div class="row">
          <div class="col-3">
            <h3 class="card-title mb-5"><%= @room.price_per_night %> $.
            </h3>
          </div>
          <div class="col-9">
            <div class="row">
              <div class="col-2" style="padding-right: 0;">
                <p>
                  <% @hotel.stars.times do %>
                  <i class="fas fa-star" style="color: #ffc107;"></i>
                  <% end %>
                </p>
              </div>
              <div class="col-10" style="padding-left: 0;">
                <p>
                  <i class="fas fa-thumbs-up"></i>
                  <%= @hotel.rating %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col">
        <%=link_to 'Edit', edit_hotel_room_path(@hotel, @room), class: 'btn btn-warning' %>
        <%=link_to 'Delete', hotel_room_path(@hotel, @room), class: 'btn btn-danger', data: {method: :delete, confirm: "Are you sure"} %>
      </div>
    </div>

    <div class="photo-gallery mb-4">
      <div class="container">
        <div class="row photos">

          <% if @room.images.attached? %>
          <% @room.images.each do |image| %>

          <div class="col-sm-6 col-md-4 col-lg-3 item">
            <%= link_to image, data: { lightbox: "room"} do %>
            <%= image_tag image, class: 'img-thumbnail' %>
            <% end %>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>



<div class="container">
  <p class="mt-0 mb-0"><b>Bed type: </b><%= @room.bed_type %></p>
    <p class="mt-0 mb-0"><b>Number of guests: </b><%= @room.number_of_people %></p>
    <p class="mt-0 mb-0"><b>Food: </b><%= @room.food %> $</p>
    <p class="mt-0 mb-0"><b>Comforts: </b><%= @room.comforts %></p>
    <p class="mt-0 mb-0"><b>Booking type: </b><%= @room.booking_type %></p>
</div>
    


  </section>

  
</div>
<% end %>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>