config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]

  resources :hotels do
    resources :rooms
    member do
      delete :purge_avatar
    end
    delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'
  end
  # resources :rooms

  namespace :admin do
    resources :users, only: %i[index create]
  end

  delete 'attachements/:id/purge', to: 'attachements#purge', as: 'purge_attachement'

  root 'hotels#index'
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar

  has_many :rooms, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2 }
  validates :stars, presence: true
end

app/controllers/hotels_controller.rb
# frozen_string_literal: true

class HotelsController < ApplicationController
  before_action :find_hotel!, only: %i[show destroy edit update]

  # before_action :authenticate_user!, only: %i[:show, :index]

  # before_filter :authenticate_user!

  def purge_avatar
    @hotel = Hotel.find params[:id]
    @hotel.avatar.purge
    flash[:success] = 'Picture deleted!'
    redirect_back fallback_location: root_path
  end

  def edit; end

  def update
    if @hotel.update hotel_params
      flash[:success] = 'Hotel saved'
      redirect_to hotel_path
    else
      render :edit
    end
  end

  def show
    @room = @hotel.rooms.build
    @pagy, @rooms = pagy @hotel.rooms.order(created_at: :desc)
  end

  def destroy
    @hotel.destroy
    flash[:success] = 'Hotel deleted!'
    redirect_to hotels_path
  end

  def index
    @pagy, @hotels = pagy Hotel.order created_at: :desc
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = current_user.hotels.build hotel_params
    if @hotel.save
      flash[:success] = 'Hotel saved!'
      redirect_to hotels_path
    else
      render :new
    end
  end

  private

  def hotel_params
    params.require(:hotel).permit(:title, :stars, :address, :link_map, :pay_one, :pay_two, :rating, :about_hotel,
                                  :services, :extra, :contacts, :avatar)
  end

  def find_hotel!
    @hotel = Hotel.find params[:id]
  end
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= render 'shared/errors', object: @hotel %>
<%= form_with model: @hotel do |f| %>
<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :title %>
  </div>
  <div class="col-sm-10">
  
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %>
  </div>
</div>

<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :stars %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :stars, placeholder: 'Stars', class: 'form-control' %>
  </div>
</div>

<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :address %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :address, placeholder: 'Address', class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :rating %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :rating, placeholder: 'Rating', class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :about_hotel %>
  </div>
  <div class="col-sm-10">
    <%= f.text_area :about_hotel, placeholder: 'About hotel', class: 'form-control' %>
  </div>
</div>

<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :services %>
  </div>
  <div class="col-sm-10">
    <%= f.text_area :services, placeholder: 'Services', class: 'form-control' %>
  </div>
</div>


<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :contacts %>
  </div>
  <div class="col-sm-10">
    <%= f.text_field :contacts, placeholder: 'Contacts', class: 'form-control' %>
  </div>
</div>

<div class="mb-3 row">
  <div class="col-sm-2 col-form-label">
    <%= f.label :avatar %>
  </div>
  <div class="col-sm-10">
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
</div>


<div class="row mt-4 mb-3" style="width: 500px;">
  <% if @hotel.avatar.attached? %>
  <%= image_tag @hotel.avatar %>
  <%= link_to "Delete image", purge_avatar_hotel_path(@hotel), method: :delete, class: "link-secondary" %>
<% end %>
</div>

<%= f.submit "Submit!", class: 'btn btn-primary' %>
<% end %>

app/views/hotels/_hotel.html.erb
<%= hotel.user.name %>
<div class="card my-3">
  <div class="row g-0">
    <div class="col-md-4 center-block p-2 h-100 d-inline-block">
      <% if hotel.avatar.attached? %>
      <%= image_tag hotel.avatar, :style => "width: 100%; height: 300px; object-fit: cover"%>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= strip_tags hotel.title %></h5>
        
        <p class="card-text">
          <% hotel.stars.times do %>
          <i class="fas fa-star" style="color: #ffc107;"></i>
          <% end %>
          <i class="fas fa-thumbs-up"></i>
          <%= hotel.rating %>
        </p>
        <p class="card-text">
          <%= truncate strip_tags(hotel.about_hotel), length: 100 %>
        </p>
        <p class="card-text">
          <small class="text-muted">
            <%= truncate strip_tags(hotel.services), length: 50 %>
          </small>
        </p>
        <%= link_to 'Show', hotel_path(hotel), class: 'btn btn-primary'%>
        <%= link_to 'Edit', edit_hotel_path(hotel), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', hotel_path(hotel), class: 'btn btn-danger', data: {method: :delete, confirm: 'Are you sure?'} %>
      </div>
    </div>
  </div>
</div>

app/views/hotels/edit.html.erb
<% provide :page_title, 'Edit hotel' %>
<% currently_at 'Hotels' %>

<h1 class="mb-4">Edit hotel</h1>

 <%= render 'form' %>

app/views/hotels/index.html.erb
<% provide :page_title, 'Hotels' %>
<% currently_at 'Hotels' %>

<div class="row mb-3">
  <div class="col-12">
    <h1>All hotels
      <%= link_to 'Create', new_hotel_path(@deed), class: 'btn btn-primary btn-sm'%>
      
    </h1>
  </div>
</div>


<%= pagination @pagy %>

<%= render @hotels %>

<%= pagination @pagy %>

app/views/hotels/new.html.erb
<% provide :page_title, 'New hotel' %>
<% currently_at 'Hotels' %>

<h1 class="mb-4">Create hotel</h1>

 <%= render 'form' %>

app/views/hotels/show.html.erb
<% provide :page_title, @hotel.title %>
<% currently_at 'Hotels' %>

<div class="card my-3">
  <div class="row g-0">
    <div class="col-md-6 center-block p-2">
      <% if @hotel.avatar.attached? %>
      <%= image_tag @hotel.avatar, :style => "width: 100%; height: 500px; object-fit: cover"%>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h3 class="card-title"><%= sanitize @hotel.title %></h3>

        <% @hotel.stars.times do %>
        <i class="fas fa-star" style="color: #ffc107;"></i>
        <% end %>
        <p class="card-text">
          <%= sanitize @hotel.address %>
        </p>
        <p class="card-text">
          <i class="fas fa-thumbs-up"></i>
          <%= @hotel.rating %>
        </p>
        <p class="card-text">
          <%= sanitize @hotel.about_hotel %>
        </p>
        <p class="card-text">
          <%= sanitize @hotel.services %>
        </p>
        <p class="card-text">
          <small class="text-muted">
            <%= sanitize @hotel.contacts %>
          </small>
        </p>
        

        <%= link_to 'Edit', edit_hotel_path(@hotel), class: 'btn btn-warning' %>
        <%= link_to 'Destroy', hotel_path(@hotel), class: 'btn btn-danger', data: {method: :delete, confirm: 'Are you sure?'} %>
      </div>
    </div>
  </div>
</div>



<hr class="my-3">



<%= render 'shared/errors', object: @room %>


<h2 class="mt-5 mb-3">Rooms <%= link_to 'Create room', new_hotel_room_path(@hotel), class: 'btn btn-secondary btn-sm' %></h2>


<%= pagination @pagy %>
<%= render partial: 'rooms/room', collection: @rooms, as: :room, locals: {hotel: @hotel} %>
<%= pagination @pagy %>